services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.11.1'
    container_name: es-local
    environment:
      # Single node configuration
      - discovery.type=single-node
      # Disable security for local development (no auth needed)
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      # Memory settings - adjust based on your system
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge